<a href="https://colab.research.google.com/github/sinsun030508/bigdata/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0_5%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40,50])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[10,20,30],[40,50,60]])
np.r_[a.reshape(-1,1), b.reshape(-1,1)]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [ ]:
np.concatenate((a.reshape(-1,1), b.reshape(-1,1)), axis=1)


array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 50]])

In [ ]:
np.c_[a,b]

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 50]])

In [ ]:
np.column_stack([a,b])

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 50]])

In [ ]:
np.concatenate((c.T, d.T), axis=1)

array([[ 1,  4, 10, 40],
       [ 2,  5, 20, 50],
       [ 3,  6, 30, 60]])

In [ ]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
c.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
patien = np.array([[1.64, 1.86, 1.63,1.76],
                   [176.0, 184.0, 169.0, 185.0]])
new_patien = patien.T
print("변경 전 다차원 배열 \n",patien)
print("번경 후 다차원 배열 \n",new_patien)


변경 전 다차원 배열 
 [[ 1.64  1.86  1.63  1.76]
 [76.   84.   69.   85.  ]]
번경 후 다차원 배열 
 [[ 1.64 76.  ]
 [ 1.86 84.  ]
 [ 1.63 69.  ]
 [ 1.76 85.  ]]


In [ ]:
result = new_patien[new_patien[:, 1] >= 75.0]
print(new_patien[new_patien >= 75.0])

[76. 84. 85.]


In [ ]:
import numpy as np

new_patien = np.array([[1.64, 1.86, 1.63, 1.76],
                       [176.0, 184.0, 169.0, 185.0]])

result = new_patien[:, new_patien[1, :] >= 175.0]

print(result)

[[  1.64   1.86   1.76]
 [176.   184.   185.  ]]


다차원 배열에서 축을 이용하여 원소를 삽입하는 방법에 대하여 알아보자


다음과 같은 다차원 배열 a 의 두 번째 원소를 2를 삽입하기 위해서는 insert() 함수를 사용함

In [ ]:
b = np.array([[1,1],[2,2],[3,3]])
np.insert(b, 1, (4,4), axis = 0)

array([[1, 1],
       [4, 4],
       [2, 2],
       [3, 3]])

In [ ]:

np.insert(b , 1, 4, axis=1)

array([[1, 4, 1],
       [2, 4, 2],
       [3, 4, 3]])