<a href="https://colab.research.google.com/github/sinsun030508/bigdata/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B04%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np_a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12],[13,14,15,16]])
print("두 번째 행, 첫 번째 원소 : ", np_a[1,0])
print("네 번째 행, 세 번째 원소 : ",np_a[3,2])




두 번째 행, 첫 번째 원소 :  5
네 번째 행, 세 번째 원소 :  15


In [ ]:
np_a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12],[13,14,15,16]])
np_array = np_a[0:2,2:4]
print(np_array)



[[3 4]
 [7 8]]
[3 4]


In [ ]:
print(np_a[0])
print(np_a[1])
print(np_a[2])
print(np_a[3])


[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [ ]:
print(np_a[0])

[1 2 3 4]


In [ ]:

print(np_a[1:])

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
print(np_a[1:, 2])

[ 7 11 15]


In [ ]:
print(np_a[1:3, 1:3])

[[ 6  7]
 [10 11]]


In [ ]:
print(np_a[::2, ::2])

[[ 1  3]
 [ 9 11]]


In [ ]:
print(np_a[::2 ])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [ ]:
print(np_a[:,2])

[ 3  7 11 15]


<h2>중간고사 시험에 나옴</h2>

In [ ]:
#1번 문제
import numpy as np
x = np.array([[0,1,2,3,4], [5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19], [20,21,22,23,24]])
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
#2번 문제
print("첫 번째 원소 : ", x[0,0])
print("마지막 원소 : ", x[4,4])
print("마지막 원소 : ", x[-1,-1])

첫 번째 원소 :  0
마지막 원소 :  24
마지막 원소 :  24


In [ ]:
#3번 문제
print(x[0:2])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
#4번 문제
print(x[2:5])

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b>6)
print(b[b>6])

[[False False False]
 [False False False]
 [ True  True  True]]
[7 8 9]


In [ ]:
print(b[:,2])
print(b[:,2]>5)
print(b[b[:,2]>5])

[3 6 9]
[False  True  True]
[[4 5 6]
 [7 8 9]]
[[1 2 3]]


In [ ]:
print(b % 2 == 0)
print(b[b % 2 == 0] )

[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]


In [ ]:
f = np.array([['a', 'f', 'c', 'd', 'c'],
              ['c', 'f', 'g', 'h', 'd']])
print("배열에서 'f' 성분을 추출한 결과 : ",f[f=='f'])
print("배열에 있는 'f' 성분의 수 : " , len(f[f=='f']))


배열에서 'f' 성분을 추출한 결과 :  ['f' 'f']
배열에 있는 'f' 성분의 수 :  2
testtest


'test'

In [ ]:
f = np.array([['a', 'f', 'c', 'd', 'c'],
              ['c', 'f', 'g', 'h', 'd']])
d = input("배열에서 찾을 성분을 입력하시오 : ")
if d in f:
  print("배열에서 '",d,"' 성분을 추출한 결과 : ",f[f==d])
else:
    print("배열에 '",d,"' 성분이 없습니다.")
print("배열에 있는 '",d,"' 성분의 수 : " , len(f[f==d]))


배열에서 찾을 성분을 입력하시오 : m
배열에 ' m ' 성분이 없습니다.
배열에 있는 ' m ' 성분의 수 :  0


In [ ]:
p = np.array([[1.63, 1.86, 1.63, 1.76],
              [76.0, 84.0, 69.0, 85.0]])
tall = p[0,:]
weight = p[1, :]
bmi = weight / tall ** 2
g = bmi[bmi<25]

print("환자들의 키 : ", tall)
print("환자들의 몸무게: ", weight)
print("환자들의 체질량지수 : ", bmi)
print("체질량지수가 25미만 값 : ", g)



환자들의 키 :  [1.63 1.86 1.63 1.76]
환자들의 몸무게:  [76. 84. 69. 85.]
환자들의 체질량지수 :  [28.60476495 24.28026361 25.97011555 27.44059917]
체질량지수가 25미만 값 :  [24.28026361]


In [ ]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
a = np.arange(2,20, 2)
print(a)


[ 2  4  6  8 10 12 14 16 18]


In [ ]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
a.reshape(-1,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])